name = "embedapi"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "EMBEDDINGS_KV"
id = "a28d90b3a35041b8ad0b0c809583726e"
preview_id = "cdba9c5a216949f180a06c36489da2fa"

[[vectorize]]
binding = "EMBEDDINGS_VECTORIZE"
index_name = "embeddings-index" 